export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const CHOOSE_SERVICE_ID = 'CHOOSE_SERVICE_ID';
export const CHANGE_SERVICE_FIELD_EDIT = 'CHANGE_SERVICE_FIELD_EDIT';
export const EDIT_SERVICE = 'EDIT_SERVICE';
export const ADD_FILTERED_VALUE = 'ADD_FILTERED_VALUE';
export const RETURN_VALUE = 'RETURN_VALUE';